source 'https://cdn.cocoapods.org/'
platform :osx, '10.15'
use_frameworks!

target 'PodTFRecords_Example' do
  pod 'PodTFRecords', :path => '../'

  target 'PodTFRecords_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.0'
    pod 'Nimble', '~> 8.0'
  end
end
